### step-1 
import libraries and load dataset

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv('raw_dataset.csv')

print("Dataset loaded successfully!")
print("Number of rows and columns:", df.shape)


df.head()

Dataset loaded successfully!
Number of rows and columns: (12575, 11)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

### Step 2 — Inspect the dataset

In [7]:
# Check column names
print(df.columns.tolist())

# Check data types and non-null values
df.info()

# Count missing values
print(df.isnull().sum())

# Count completely duplicated rows
print("Duplicate rows:", df.duplicated().sum())

# Summary of numerical columns
display(df.describe())

['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit', 'Quantity', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date', 'Discount Applied']
<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.1+ MB
Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64
Duplicate rows: 0

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

### step-3 Identify problem

In [8]:
# Find blank or whitespace-only cells
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].replace(r"^\s*$", np.nan, regex=True)

print(df.isnull().sum())

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

C:\Users\nks00\AppData\Local\Temp\ipykernel_19684\905028749.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

### Step -4 Handle Missing values

In [9]:
 # Investigate missing values in percentages
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

display(missing_summary)

                  Missing Count  Missing Percentage
Transaction ID                0                0.00
Customer ID                   0                0.00
Category                      0                0.00
Item                       1213                9.65
Price Per Unit              609                4.84
Quantity                    604                4.80
Total Spent                 604                4.80
Payment Method                0                0.00
Location                      0                0.00
Transaction Date              0                0.00
Discount Applied           4199               33.39

In [10]:
# Display the first 10 rows with missing values
display(df[df.isnull().any(axis=1)].head(10))

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
14,TXN_2490363,CUST_09,Milk Products,Item_16_MILK,27.5,2.0,55.0,Digital Wallet,Online,2022-05-22,NaN
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False
20,TXN_9939063,CUST_14,Beverages,Item_7_BEV,14.0,9.0,126.0,Digital Wallet,In-store,2024-01-14,NaN
21,TXN_8685338,CUST_15,Milk Products,NaN,NaN,3.0,105.0,Credit Card,In-store,2023-10-29,NaN

### Step-5 checking the missing values before fixing them

In [11]:
# Check whether missing values occur together
missing_rows = df[df.isnull().any(axis=1)]

display(
    missing_rows[
        ["Item", "Category", "Price Per Unit",
         "Quantity", "Total Spent", "Discount Applied"]
    ].head(20)
)

,Item,Category,Price Per Unit,Quantity,Total Spent,Discount Applied
3,Item_16_BEV,Beverages,27.5,9.0,247.5,NaN
5,NaN,Patisserie,NaN,10.0,200.0,NaN
7,NaN,Furniture,33.5,NaN,NaN,True
11,NaN,Milk Products,NaN,8.0,52.0,True
14,Item_16_MILK,Milk Products,27.5,2.0,55.0,NaN
15,NaN,Beverages,24.5,NaN,NaN,NaN
17,NaN,Milk Products,NaN,10.0,275.0,NaN
19,NaN,Furniture,35.0,NaN,NaN,False
20,Item_7_BEV,Beverages,14.0,9.0,126.0,NaN
21,NaN,Milk Products,NaN,3.0,105.0,NaN
22,Item_4_EHE,Electric household essentials,9.5,7.0,66.5,NaN
25,NaN,Furniture,39.5,NaN,NaN,False
32,NaN,Food,NaN,8.0,196.0,True
33,Item_21_EHE,Electric household essentials,35.0,9.0,315.0,NaN
34,NaN,Patisserie,23.0,NaN,NaN,NaN
38,Item_11_BEV,Beverages,20.0,5.0,100.0,NaN
41,Item_10_EHE,Electric household essentials,18.5,5.0,92.5,NaN
42,Item_24_BUT,Butchers,39.5,7.0,276.5,NaN
43,Item_8_BEV,Beverages,15.5,3.0,46.5,NaN
44,Item_3_FOOD,Food,8.0,1.0,8.0,NaN

In [12]:
# Now investigate Discount Applied seprately
print("Discount Applied values:")
print(df["Discount Applied"].value_counts(dropna=False))

print("\nData type:")
print(df["Discount Applied"].dtype)

Discount Applied values:
Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

Data type:
object

### step -6 check incorrect and inconsistent values

In [13]:
# Check numeric values
print("Price Per Unit:")
print(df["Price Per Unit"].describe())

print("\nQuantity:")
print(df["Quantity"].describe())

print("\nTotal Spent:")
print(df["Total Spent"].describe())

# Check for zero or negative values
print(
    "Non-positive prices:",
    (df["Price Per Unit"] <= 0).sum()
)

print(
    "Non-positive quantities:",
    (df["Quantity"] <= 0).sum()
)

Price Per Unit:
count    11966.000000
mean        23.365912
std         10.743519
min          5.000000
25%         14.000000
50%         23.000000
75%         33.500000
max         41.000000
Name: Price Per Unit, dtype: float64

Quantity:
count    11971.000000
mean         5.536380
std          2.857883
min          1.000000
25%          3.000000
50%          6.000000
75%          8.000000
max         10.000000
Name: Quantity, dtype: float64

Total Spent:
count    11971.000000
mean       129.652577
std         94.750697
min          5.000000
25%         51.000000
50%        108.500000
75%        192.000000
max        410.000000
Name: Total Spent, dtype: float64
Non-positive prices: 0
Non-positive quantities: 0

In [14]:
#Check inconsistent text
for col in [
    "Category", "Payment Method", "Location", "Item"
]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(20))

--- Category ---
Category
Furniture                             1591
Electric household essentials         1591
Food                                  1588
Milk Products                         1584
Butchers                              1568
Beverages                             1567
Computers and electric accessories    1558
Patisserie                            1528
Name: count, dtype: int64

--- Payment Method ---
Payment Method
Cash              4310
Digital Wallet    4144
Credit Card       4121
Name: count, dtype: int64

--- Location ---
Location
Online      6354
In-store    6221
Name: count, dtype: int64

--- Item ---
Item
NaN             1213
Item_2_BEV       126
Item_25_FUR      113
Item_11_FUR      110
Item_16_MILK     109
Item_1_MILK      109
Item_20_BUT      107
Item_5_FUR       107
Item_14_FOOD     106
Item_11_MILK     106
Item_19_CEA      106
Item_19_MILK     105
Item_24_FUR      105
Item_8_EHE       105
Item_13_FOOD     101
Item_12_CEA      101
Item_22_BUT      100
Item_12_PAT      100
Item_14_BEV      100
Item_5_CEA        98
Name: count, dtype: int64

In [15]:
#Check transaction dates
print(df["Transaction Date"].head(10))

parsed_dates = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce"
)

print("Dates that cannot be parsed:", parsed_dates.isna().sum())

0    2024-04-08
1    2023-07-23
2    2022-10-05
3    2022-05-07
4    2022-10-02
5    2023-11-30
6    2023-06-10
7    2024-04-02
8    2023-04-26
9    2024-03-14
Name: Transaction Date, dtype: str
Dates that cannot be parsed: 0

### Step 7 — Check whether the totals are correct

In [16]:
check = df.dropna(
    subset=["Price Per Unit", "Quantity", "Total Spent"]
).copy()

check["Calculated Total"] = (
    check["Price Per Unit"] * check["Quantity"]
)

check["Difference"] = (
    check["Total Spent"] - check["Calculated Total"]
).round(2)

display(
    check.loc[
        check["Difference"].abs() > 0.01,
        ["Price Per Unit", "Quantity",
         "Total Spent", "Calculated Total", "Difference"]
    ].head(20)
)

Empty DataFrame
Columns: [Price Per Unit, Quantity, Total Spent, Calculated Total, Difference]
Index: []

In [17]:
 # Investigate missing values in percentages
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

display(missing_summary)

                  Missing Count  Missing Percentage
Transaction ID                0                0.00
Customer ID                   0                0.00
Category                      0                0.00
Item                       1213                9.65
Price Per Unit              609                4.84
Quantity                    604                4.80
Total Spent                 604                4.80
Payment Method                0                0.00
Location                      0                0.00
Transaction Date              0                0.00
Discount Applied           4199               33.39

In [18]:
# Preserve the original data in memory
df_raw = df.copy(deep=True)

# Work on a separate copy
df_clean = df.copy(deep=True)

print("Original shape:", df_raw.shape)
print("Working copy shape:", df_clean.shape)

Original shape: (12575, 11)
Working copy shape: (12575, 11)

In [19]:
text_columns = df_clean.select_dtypes(
    include=["object", "string"]
).columns

for col in text_columns:
    df_clean[col] = df_clean[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

print("Unnecessary surrounding spaces removed.")

Unnecessary surrounding spaces removed.

In [20]:
df_clean["Transaction Date Parsed"] = pd.to_datetime(
    df_clean["Transaction Date"],
    errors="coerce"
)

invalid_dates = (
    df_clean["Transaction Date"].notna()
    & df_clean["Transaction Date Parsed"].isna()
)

print("Invalid dates:", invalid_dates.sum())
display(df_clean.loc[invalid_dates, ["Transaction Date"]].head(20))

Invalid dates: 0

Empty DataFrame
Columns: [Transaction Date]
Index: []

In [21]:
# Run only after verifying the date format
if not invalid_dates.any():
    df_clean["Transaction Date"] = df_clean.pop(
        "Transaction Date Parsed"
    )

In [22]:
missing_summary = pd.DataFrame({
    "Missing Count": df_clean.isnull().sum(),
    "Missing Percentage": (
        df_clean.isnull().mean() * 100
    ).round(2)
})

display(missing_summary)

                  Missing Count  Missing Percentage
Transaction ID                0                0.00
Customer ID                   0                0.00
Category                      0                0.00
Item                       1213                9.65
Price Per Unit              609                4.84
Quantity                    604                4.80
Total Spent                 604                4.80
Payment Method                0                0.00
Location                      0                0.00
Transaction Date              0                0.00
Discount Applied           4199               33.39

In [23]:
display(
    df_clean.loc[
        df_clean.isnull().any(axis=1),
        [
            "Transaction ID",
            "Category",
            "Item",
            "Price Per Unit",
            "Quantity",
            "Total Spent",
            "Discount Applied"
        ]
    ].head(20)
)

,Transaction ID,Category,Item,Price Per Unit,Quantity,Total Spent,Discount Applied
3,TXN_9458126,Beverages,Item_16_BEV,27.5,9.0,247.5,NaN
5,TXN_7482416,Patisserie,NaN,NaN,10.0,200.0,NaN
7,TXN_1372952,Furniture,NaN,33.5,NaN,NaN,True
11,TXN_5422631,Milk Products,NaN,NaN,8.0,52.0,True
14,TXN_2490363,Milk Products,Item_16_MILK,27.5,2.0,55.0,NaN
15,TXN_1809665,Beverages,NaN,24.5,NaN,NaN,NaN
17,TXN_9634894,Milk Products,NaN,NaN,10.0,275.0,NaN
19,TXN_4206593,Furniture,NaN,35.0,NaN,NaN,False
20,TXN_9939063,Beverages,Item_7_BEV,14.0,9.0,126.0,NaN
21,TXN_8685338,Milk Products,NaN,NaN,3.0,105.0,NaN
22,TXN_6547964,Electric household essentials,Item_4_EHE,9.5,7.0,66.5,NaN
25,TXN_3481599,Furniture,NaN,39.5,NaN,NaN,False
32,TXN_1543244,Food,NaN,NaN,8.0,196.0,True
33,TXN_1494700,Electric household essentials,Item_21_EHE,35.0,9.0,315.0,NaN
34,TXN_1621497,Patisserie,NaN,23.0,NaN,NaN,NaN
38,TXN_8312797,Beverages,Item_11_BEV,20.0,5.0,100.0,NaN
41,TXN_1019817,Electric household essentials,Item_10_EHE,18.5,5.0,92.5,NaN
42,TXN_1110407,Butchers,Item_24_BUT,39.5,7.0,276.5,NaN
43,TXN_6276518,Beverages,Item_8_BEV,15.5,3.0,46.5,NaN
44,TXN_4740738,Food,Item_3_FOOD,8.0,1.0,8.0,NaN

In [32]:
print(
    df_clean["Discount Applied"]
    .value_counts(dropna=False)
)

Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

In [25]:
check = df_clean.dropna(
    subset=["Price Per Unit", "Quantity", "Total Spent"]
).copy()

check["Calculated Total"] = (
    check["Price Per Unit"] * check["Quantity"]
).round(2)

check["Difference"] = (
    check["Total Spent"] - check["Calculated Total"]
).round(2)

inconsistent_totals = check[
    check["Difference"].abs() > 0.01
]

print("Records checked:", len(check))
print("Inconsistent totals:", len(inconsistent_totals))

display(
    inconsistent_totals[
        [
            "Transaction ID",
            "Price Per Unit",
            "Quantity",
            "Total Spent",
            "Calculated Total",
            "Difference"
        ]
    ].head(30)
)

Records checked: 11362
Inconsistent totals: 0

Empty DataFrame
Columns: [Transaction ID, Price Per Unit, Quantity, Total Spent, Calculated Total, Difference]
Index: []

In [26]:
print("Exact duplicate rows:", df_clean.duplicated().sum())

for col in ["Price Per Unit", "Quantity", "Total Spent"]:
    print(f"\n{col}")
    print(df_clean[col].describe())
    print("Negative values:", (df_clean[col] < 0).sum())
    print("Zero values:", (df_clean[col] == 0).sum())

Exact duplicate rows: 0

Price Per Unit
count    11966.000000
mean        23.365912
std         10.743519
min          5.000000
25%         14.000000
50%         23.000000
75%         33.500000
max         41.000000
Name: Price Per Unit, dtype: float64
Negative values: 0
Zero values: 0

Quantity
count    11971.000000
mean         5.536380
std          2.857883
min          1.000000
25%          3.000000
50%          6.000000
75%          8.000000
max         10.000000
Name: Quantity, dtype: float64
Negative values: 0
Zero values: 0

Total Spent
count    11971.000000
mean       129.652577
std         94.750697
min          5.000000
25%         51.000000
50%        108.500000
75%        192.000000
max        410.000000
Name: Total Spent, dtype: float64
Negative values: 0
Zero values: 0

In [27]:
df_clean.to_csv(
    "cleaning_review.csv",
    index=False
)

print("Review copy saved.")
print("Original rows:", len(df_raw))
print("Review rows:", len(df_clean))

Review copy saved.
Original rows: 12575
Review rows: 12575